version: "3.8"

services:
  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile.user
    container_name: user-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI:
      - PORT: 8080

  nginx:
    build: ./nginx
    container_name: nginx-gateway
    restart: always
    ports:
      - "80:80"
    environment:
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: 8080
      POST_SERVICE_HOST:
      POST_SERVICE_PORT:
    depends_on:
      - user-service
