global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "cadvisor-manager"
    static_configs:
      - targets: ["cadvisor-manager:8080"]

  - job_name: "cadvisor-worker"
    static_configs:
      - targets: ["192.168.56.102:8080"]
